version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery_app worker -l info
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data: 