version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    command: poetry run celery -A app.worker.celery_app worker --loglevel=info

volumes:
  mongo_data: 